### ISSUE TITLE
Anyone else experiencing a memory leak?

### ISSUE THREAD

**Issue by activeshadow** [NREL/OpenDSSDirect.py#16]
- Python version: 3.5.1
- Python architecture x64
- Operating system and version: Ubuntu 16.04 LTS
- OpenDSSDirect.py version: 0.2.10

I'm experiencing a memory leak within my Python application that's using OpenDSSDirect. The application is constantly making calls into the OpenDSS library to update VV curves and trigger solves. Prior to starting the loop for updating curves and solving, everything is fine. Once that loop starts, memory consumption starts to increase steadily.

I'm under the impression that, while it's not impossible, it's pretty hard to have a memory leak within Python. So my guess is there's a memory leak within the actual OpenDSS Delphi code, but I thought I'd start here first to see if anyone else has experienced it.

I'm also in no way saying there's not a problem with my Python code that's using/calling the OpenDSSDirect library... but I have yet to see one that would cause a memory leak.

**Comment by kdheepak** [comment]
@activeshadow This is definitely an issue that other people have reported as well. See [this thread on the official forum](https://sourceforge.net/p/electricdss/discussion/experts/thread/89f78cd6/) for some more information on this. I have a couple of ideas in mind on how to profile this to get more information on what is going on. Last year, I did run a memory profiler in pascal on a few functions in OpenDSS source code and found some memory leaks, but at the time it was still unclear whether this was a fpc issue or not. But, while searching for the thread above today I found [this more recent thread](https://sourceforge.net/p/electricdss/discussion/experts/thread/f9981d95/) which says that they may have fixed some leaks in the most recent version of OpenDSS. Maybe this could solve all these issues? I had issues compiling the most recent version of OpenDSS in the past, but I'll try it again and see if I can get a new release out today. 

It is also very possible that there are some issues with this package. When I wrote this the last year it was my first time interfacing with libraries and it is very possible that I missed some crucial details. Last week I was prototyping a rewrite while maintaining the same / very similar interface of this package in order to aid debugging/profiling the memory leaks. I don't have anything substantive yet, but I'll post updates on this thread.

**Comment by activeshadow** [comment]
@kdheepak thanks for the response. Yeah, looks like version 8 of OpenDSS might be the solution. Too bad they don't yet offer macOS and Linux DLLs like you requested back in November.

I would be very much appreciative if you were able to get a new release out today, but understand if you're having compile issues. I've *never* worked with Pascal before, so not sure I'd be much help, but let me know if there's anything you think I can do.

**Comment by activeshadow** [comment]
@kdheepak hmmm... reading over the threads you referenced again, I notice both threads talk about clearing the existing circuits since they're doing large numbers of simulations across different circuits.

In my case, we're solving for different permutations of the same circuit (ie. different VV curves). Should I still be clearing circuits out and loading them again each time I want to solve a different permutation?

Perhaps I'm going down a rabbit hole that I don't need to. Hopefully version 8 of OpenDSS will solve the memory leak(s), even when solving the same circuit multiple times.

**Comment by kdheepak** [comment]
My understanding was that using the `clearall` to clear the circuits was a definitive way to clearing the memory used by OpenDSS. Let's see what happens with v8, since that could be a low effort solution to this problem.

With regards to a scenario where you are doing permutations of some parameters, I personally tend to rebuild the circuit for quick simulations since it is the easiest way to ensure deterministic results for a given set of parameters. However, with different feeder sizes this may not always be practical. In terms of memory and performance, ideally it'd be lower CPU cycles to change an existing circuit than rebuilding it. However if there are memory leaks occurring every time a OpenDSS function is called, and if the `clearall` command works correctly, you may have to rebuild depending on the number on permutations of parameters you have. Hope that answers your question?

**Comment by activeshadow** [comment]
Thanks @kdheepak. I'll leave my code as-is and test it against v8 once you're able to release a new version of OpenDSSDirect that uses v8.

If simply upgrading to v8 doesn't solve the memory leak I'm seeing, I'll update my code to clear and rebuild the circuit each time.

**Comment by kdheepak** [comment]
@activeshadow I'm able to compile the latest v7 but haven't been able to get v8 working yet. Also, I haven't checked this repository yet by @PMeira, it appears @PMeira has been able to compile OpenDSS with v7 and including experimental support for v8. You can find that repo over [here](https://github.com/PMeira/dss_python/). This could potentially solve your memory issues, but depending on how much work you have already done using this package, this may require some rewriting of your code. We have started discussing potentially working together on having one codebase for OpenDSS in Python. You can follow that conversation [in this thread](https://github.com/PMeira/dss_python/issues/8). I'll continue working on trying to get v8 working here and post updates when I have them.

**Comment by activeshadow** [comment]
OK. The memory leak(s) the OpenDSS folks knew of weren't addressed until v8, correct?

From your previous comments, it sounds like I could take the `clearall` approach to get things working in v7. Am I understanding that correctly?

**Comment by activeshadow** [comment]
Do you plan on publishing a release with your latest v7 DLL? If so, will it just be here in GitHub or will it be in the Python repos as well?

**Comment by kdheepak** [comment]
When I publish it, I'll make it available on Windows, Mac and Linux using the GitHub and via PyPi. I haven't gotten around to compile it on Linux yet, I'm just testing this on my Mac at the moment. 

You can try the `clearall` method. I have a vague recollection that when a colleague of mine tried the same thing, it didn't actually solve the problem, but I may be misremembering. Sorry that that is not really helpful. 

I've made some progress compiling what I think is OpenDSS v8 but I'm still stuck. I'll have more concrete answers by the end of the day for your best short term and long term strategy.

**Comment by activeshadow** [comment]
@kdheepak using the `clearall` method did seem to eliminate the memory leak, though doing so does slow down the simulation considerably. Roughly 2 additional seconds are required per update now (for this particular circuit) to compile the circuit from file, solve it, save it back to file (to be used for the next update), and clear the circuit.

Thanks for the help! I look forward to testing out v8 to see if I can avoid the extra compile, save, and clear steps per update, but until then this approach will work fine!

**Comment by PMeira** [comment]
Hi!
As @kdheepak mentioned, I did port the v8/PM months ago but a lot of things changed. I hoped that they'd consider part of my changes, but the v8 code base is not friendly to FreePascal even on Windows and there are still several other minor differences (I posted them in a new thread on the official OpenDSS forum some days ago). The first release of v8 had a lot more issues but I guess most of them are already fixed. 

Since I didn't keep track of the official changes as they were introduced, I had to reapply my own changes carefully. To avoid the mistake again, I started a new repository at https://github.com/PMeira/electricdss-src/ 


Note that the official v8 repo won't build at all on Linux/Mac. Besides some FreePascal, we need to add the proper process/thread handling. I did add a partial implementation in https://github.com/PMeira/electricdss-src/commit/5273247908f92943647c09d4e9d3db669e23c818, besides many other small changes scattered in my other commits.


Right now I'm retesting and fixing remaining issues I find in v8 (v7 is running fine). I'm not testing on Linux initially, but the basics (most of the test cases) are running fine on Windows. As soon as I get it to mostly work, I'll move back to working in dss_python and integrating the OpenDSSDirect.py API.

> From your previous comments, it sounds like I could take the clearall approach to get things working in v7. Am I understanding that correctly?

@activeshadow Interesting, the sample code I used to test that didn't leak on v7 and Windows. Is it easy to reproduce the leak? If so, I can look into it. I already backported some changes in v8 to v7.

**Comment by activeshadow** [comment]
@PMeira unfortunately it's not easy to reproduce the leak. Also, we're running on Linux, so perhaps that's where some of the leak issues lie, since you didn't see a leak on v7 in Windows.

I'm also assuming that version 0.2.10 of OpenDSSDirect.py is using v7... perhaps it's using v6?

**Comment by kdheepak** [comment]
The libraries for Mac and Linux used in OpenDSSDirect.py are from the tag number `r2092`, which some minor changes that I made manually. I'm not sure exactly which "version" of OpenDSS that is though. 

@PMeira Is your plan to maintain a fork of the electricdss repository with changes to make them work cross platform? Also, do you have a plan for how you plan to integrate the interface in OpenDSSDirect.py? Are you planning to contribute back to this repository? I'd be up to discuss this (perhaps over the phone?) if that will make this conversation easier and more productive.

**Comment by kdheepak** [comment]
It turns out that Python/ctypes does not free memory that was not allocated by it. This makes more sense than what I thought was happening, i.e. Python keeping track for the pointers and knowing how to free them once they went out of scope. Since OpenDSS allocates memory, OpenDSS should free the memory as well. I did not implement this and currently I am not freeing any memory manually, i.e. I'm only using the functions that were exposed by the OpenDSSDirect library by default. This means that using OpenDSSDirect.py **will** leak memory. I'll work towards implementing these fixes. Pinging @tshort since it might be relevant.

**Comment by kdheepak** [comment]
@PMeira I see that you've written out these functions manually already implemented in [dss_capi](https://github.com/PMeira/dss_capi/blob/e6e551d/src/main/CAPI_Utils.pas). Are you planning to make these contributions back to the electricdss repository?

**Comment by PMeira** [comment]
> unfortunately it's not easy to reproduce the leak. Also, we're running on Linux, so perhaps that's where some of the leak issues lie, since you didn't see a leak on v7 in Windows.

@activeshadow Ah, I see. I do use it on Linux too (on a small cluster) but probably our code doesn't trigger the leak. Still, the fact that `ClearAll` prevents the leak might help finding the issue.

> Is your plan to maintain a fork of the electricdss repository with changes to make them work cross platform? 

@kdheepak Not really sure yet, I'm sending you an email in a couple of minutes (to the email address listed on your website).

> I see that you've written out these functions manually already implemented in dss_capi. Are you planning to make these contributions back to the electricdss repository?

If there is interest, sure. There is nothing special about them, just copying the whole folder and changing the `.lpr` and `.cfg` files is enough to move them. I kept the same license too. The patches to the main codebase (that now live as the [new repo](https://github.com/PMeira/electricdss-src/)) are essential for building with FreePascal though, so...

**Comment by kdheepak** [comment]
I see, so if my understanding is correct `electricdss-src` is the original source code with patches to make it work for FPC and `dss_capi` is your implementation of the DSS api aiming for COM compatibility. That email will work to contact me. Let's discuss more over email.

**Comment by PMeira** [comment]
> I see, so if my understanding is correct electricdss-src is the original source code with patches to make it work for FPC and dss_capi is your implementation of the DSS api aiming for COM compatibility. 

Just to confirm, yes, exactly. 
I'm still evaluating if either including `electricdss-src` as a Git submodule is a good idea to simplify the build instructions, or even merging `electricdss-src` and `dss_capi` in a single repo later.

(Even if all changes were accepted upstream, SVN is not that convenient.)

**Comment by kdheepak** [comment]
This should be resolved now in v0.3.0, thanks to the excellent work of @PMeira.

**Comment by activeshadow** [comment]
Thanks @kdheepak and @PMeira! I'll try to test w/in the next few days and let you know if the (perceived) memory leak I was seeing when I opened this issue still exists.

More to come...

**Comment by kdheepak** [comment]
Great! Feel free to reopen if you still experience these issues.

**Comment by activeshadow** [comment]
@kdheepak I'm getting the following when I run `python setup.py install` against a project that requires OpenDSSDirect.py.
```
Searching for dss_python
Reading https://pypi.python.org/simple/dss_python/
No local packages or download links found for dss_python
error: Could not find suitable distribution for Requirement.parse('dss_python')
```
My setup file includes the following...
```
requires = [
    ...
    'numpy==1.11.2',
    'opendssdirect.py==0.3.0',
    ....
]
```

Build environment is an Ubuntu 16.04 Docker image with `python3, python3-dev, python3-setuptools, and python3-numpy` installed. Worked with `OpenDssDirect.py v0.2.10`. Ideas?

**Comment by kdheepak** [comment]
Can you tell us which version of Python you are using? Python <= 3.4 might not be supported at the moment. I believe we can add it, but will have to check with @PMeira to be certain.

**Comment by activeshadow** [comment]
@kdheepak 
```
root@d692953164e6:/# python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by activeshadow** [comment]
It installs fine with pip. Must be something with setuptools?

**Comment by PMeira** [comment]
I had issues with that installing other modules, usually running `pip install .` instead of `python setup.py install` is enough. 

The issue here is that old setuptools (got version 20 in my test Ubuntu 16 installation) doesn't support wheels. Tested installing the newest (40) and it managed to find and install the wheel fine.  The relevant changes are from Nov 2017 (seems to be https://github.com/pypa/setuptools/pull/1200), probably too recent.

One giveaway was that it searched the old domain:

> Reading https://pypi.python.org/simple/dss_python/

Recent releases use the new top-level domain:

> Reading https://pypi.org/simple/dss_python/

**Comment by activeshadow** [comment]
@PMeira I totally missed your suggestion of running `pip install .` in place of `python3 setup.py install`.

That worked, thanks! Closing.
